### ISSUE TITLE
Convert .atn to .jsx breaks in CC2019

### ISSUE THREAD

**Issue by speedgeil** [tonton-pixel/JSON-Photoshop-Scripting#2]
Hi Michel!

I really love your Action Converter and i need it for building my html panel.
When i start converting the actions it converts some actions but others not. When it stops converting, photoshop freezes and must be killed via Taskmanager. Interestingly when it stops working the last file it converted is 32.768KB big. No matter on which file this happens.
I would be really glad if you could point this out.

Regards from Germany 
André

**Comment by tonton-pixel** [comment]
Hi André,

Well, as you may have noticed, I kind of stopped working on this project many years ago, when it became just impossible to upgrade my Basic Creative Suite CS4 (Photoshop, Illustrator, inDesign) to CS6, thanks to Adobe's new commercial policy promoting *renting* software instead of *buying* it...

I have no idea whether the problem you're encountering is specific or not to the latest versions of Photohop, but I remember that converting some action files would sometimes literally take *hours*, especially when they were containing large chunks of binary data such as **color profiles**. I don't know if the old JavaScript engine used by Photoshop for scripting is still the same now, but it had terrible performance issues when dealing with very long strings. And not only for my scripts, but also for others, such as Xbytor's set of [xtools](http://ps-scripts.sourceforge.net/xtools.html)...

In such situations, Photoshop would appear to be *frozen* but would actually be very *buzy*...

As for the 32.768KB size, it may indicate some hard limit indeed, but I must confess that I have no clue whatsoever...

Regards,

    --Michel

**Comment by speedgeil** [comment]
Hi Michel! Thank you for answering.

I tried xbytor's script as well. And it shows same symptoms , as you expected.
I found an old copy of CS6 on one of my HD's and tried it. But same behaviour. I might try to convert an action over night. What i can tell is that photoshop freezes but the process still takes 15% CPU in Taskmanager. 
Maybe i find a copy of CS4 somewhere on the web and try that.

Regards André
